import { z } from "zod";

export const SubSkillTypeEnum = z.enum([
	"Area of Effect Damage Up",
	"Damage Up",
	"Attack Speed Up",
	"Stun Chance",
	"Defense Up",
	"Damage Taken Down",
	"Enemy Troops Attack Down",
	"Heal Up",
	"Health Up",
	"Healing Speed Up",
	"Hunting Income",
	"Meat Gathering Speed",
	"Crit Rate",
	"Stamina Cost Down",
	"Wilderness March Speed",
	"Stun Time",
	"Coal Mine Income",
	"Coal Gathering Speed",
	"Iron Mine Income",
	"Iron Gathering Speed",
	"Enemy Damage Taken Up",
	"Logging Income",
	"Wood Gathering Speed",
	"Reduces Enemy Attack",
	"Enemy Damage Down",
	"Wilderness March Speed",
	"2nd Bullet Damage Up",
	"3nd Bullet Damage Up",
	"Enemy Attack Speed Down",
	"Increases Research Speed",
	"Construction Cost Down",
	"Construction Speed Up",
	"Training Speed Up",
	"No. of Attacks",
]);

export type SubSkillType = z.infer<typeof SubSkillTypeEnum>;
